export const TEXT_CONTENT_LIST_REQUEST = 'TEXT_CONTENT_LIST_REQUEST';
export const TEXT_CONTENT_LIST_SUCCESS = 'TEXT_CONTENT_LIST_SUCCESS';
export const TEXT_CONTENT_LIST_FAIL = 'TEXT_CONTENT_LIST_FAIL';