export const PERSONAL_CONTENT_LIST_REQUEST = 'PERSONAL_CONTENT_LIST_REQUEST';
export const PERSONAL_CONTENT_LIST_SUCCESS = 'PERSONAL_CONTENT_LIST_SUCCESS';
export const PERSONAL_CONTENT_LIST_FAIL = 'PERSONAL_CONTENT_LIST_FAIL';