import React from 'react'

export default function TermsConditionsScreen() {
    return (
        <>
            <section className="uk-section uk-background-primary">
                <div className="uk-container uk-text-center" uk-scrollspy="cls: uk-animation-fade; delay: 300; repeat:true;">
                    <h4 className="uk-margin-remove">Terms & Conditions</h4>
                    <h1 className="uk-margin-remove">How can I find out your terms?</h1>
                </div>
            </section>
            <section className="uk-section">
                <div className="uk-container">
                    <div className="uk-grid-medium" uk-grid="true">
                        <div className="uk-width-1-1" uk-scrollspy="cls: uk-animation-fade; delay: 300; repeat:true;">
                            <h4 className="uk-text-muted">Definitions</h4>
                            <p>In the present general terms and conditions, the following terms are used in the sense given below, unless explicitly indicated otherwise.EIPA: the user of the general terms and conditions. Client: EIPA’s opposite party. Agreement: the agreement concerning the provision of services.</p>
                            <h4 className="uk-text-muted">General</h4>
                            <p>The present terms and conditions shall apply to each and every offer, tender and agreement between EIPA and a client, to which EIPA has declared the present terms and conditions applicable, insofar as parties have not explicitly deviated from the present terms and conditions in writing. The present terms and conditions shall also apply to all agreements with EIPA, the execution of which calls for the services of third parties. Possible deviations from the present general terms and conditions shall only be valid provided they have been explicitly agreed upon in writing. The applicability of client’s possible purchase or other conditions is explicitly rejected. If one or more stipulations in the present general terms and conditions should be null and void or declared null and void, then the other stipulations of the present general terms and conditions shall remain fully applicable. The case ensuing, EIPA and client shall enter into negotiations to agree upon new stipulations replacing the null and void conditions, or, as the case may be, the conditions declared null and void, whereby the purpose and the meaning of the original conditions shall be heeded as far as possible.</p>
                            <h4 className="uk-text-muted">Offers and Tenders</h4>
                            <p>All offers shall be free of obligation unless the offer contains an acceptance term. The offers made by EIPA shall be free of obligation; they shall be valid for a period of 60 days, unless indicated otherwise. EIPA shall only be bound by the offers if the acceptance thereof is confirmed in writing by the opposite party within 60 days, unless indicated otherwise. The prices given in above-mentioned offers and tenders shall be exclusive of and not subject to VAT and other government levies, as well as of the other expenses to be possibly made within the scope of the agreement, including shipment and administration costs, unless EIPA indicates otherwise. If the acceptance deviates (on secondary items) from the offer given, EIPA shall not be bound by it. The agreement shall in such event not be concluded in accordance with said deviating acceptance, unless EIPA indicates otherwise. A compound quotation shall not oblige EIPA to execute part of the assignment against a corresponding part of the given quotation. Offers and tenders shall not apply automatically to future assignments.</p>
                            <h4 className="uk-text-muted">Execution of the Agreement</h4>
                            <p>EIPA shall execute the agreement to the best of his knowledge and ability. If and in so far required for the proper execution of the agreement, EIPA shall have the right to have certain work done by third parties. The client shall see to it that EIPA shall be provided in due time with all data which EIPA has said to be necessary or which the client must in all reasonableness understand to be necessary to the execution of the agreement. If EIPA has not been provided in due time with the data necessary to the execution of the agreement, EIPA shall have the right to suspend the execution of the agreement and / or to charge the client for the additional costs resulting from the delay at the generally accepted rates. EIPA shall not be liable for damage of whatever nature caused by the fact that EIPA worked on the basis of incorrect and / or incomplete data provided by the client, unless EIPA should have been aware of said incorrectness or incompleteness. If parties have agreed that the agreement will be executed in stages, EIPA can suspend the execution of the parts belonging to a following stage until the client has approved in writing the results of the stage prior to it. If EIPA or third parties engaged by EIPA within the scope of the assignment do work at client’s site or at a site designated by client, client shall provide the employees having to work there free of charge with all facilities desired in all reasonableness by said employees. Client shall safeguard EIPA against possible claims filed by third parties who may sustain damage attributable to client in connection with the execution of the agreement.</p>
                            <h4 className="uk-text-muted">Changes to the agreement</h4>
                            <p>If it is shown during the execution of the agreement that the work to be done needs to be changed and supplemented in order to ensure its proper execution, parties shall adapt the agreement accordingly in due time and in mutual consultations. If parties agree that the agreement needs to be changed or supplemented, this decision may influence the time of completion of the execution. EIPA shall inform the client thereof as soon as possible. Should the change or supplement to the agreement have any financial and / or qualitative consequences, EIPA shall inform client thereof in advance. If a fixed fee has been agreed upon then EIPA shall indicate the degree to which the change or supplement to the agreement will result in an increase of said fee. Contrary to the conditions of paragraph 3, EIPA shall not be able to charge additional costs if the change or supplement is the result of circumstances attributable to EIPA.</p>
                            <h4 className="uk-text-muted">Duration of the Contract; Term of Execution</h4>
                            <p>The agreement between EIPA and a client shall be entered into for an indefinite period of time, unless the nature of the agreement dictates otherwise or if parties have explicitly agreed otherwise in writing. If a term has been agreed to complete certain work within the term of the agreement, then this term shall never be a term to be observed on penalty of forfeiture of rights. If the term of execution is exceeded, the client must consequently declare EIPA in default in writing.</p>
                            <h4 className="uk-text-muted">Fee and costs</h4>
                            <p>Parties agree upon a fixed fee the moment the agreement is concluded. If no fixed fee has been agreed upon, the fee shall be determined on the basis of the number of hours/days actually spent on the work. The fee shall be calculated in accordance with EIPA’s usual rates, valid for the period in which the work is being done, unless a deviating rate has been agreed upon. The fee and a possible cost estimate shall be exclusive of and not subject to VAT. With respect to assignments with duration of more than three months, the costs owed shall be charged periodically. If EIPA and the client agree upon a fixed fee or an hourly/daily rate, EIPA shall nevertheless be entitled to increase this fee or rate. EIPA shall be allowed to charge on price increases, if changes in price have occurred between the time of offer and the time of delivery with respect to, e.g., salaries and wages as well as if the power to increase the price is the result of a power given to the EIPA by law or if the EIPA is obligated to increase the price by (virtue of) law. EIPA shall furthermore be able to increase the fee when it is shown during the execution of the work that the volume of work initially agreed upon or expected when the contract was concluded, was underestimated to such a degree, and this through no fault of the EIPA, that EIPA cannot be expected in reasonableness to do the work agreed upon for the fee initially agreed upon. In hat case EIPA shall notify the client of his intention to increase the fee or the hourly/daily rate, whereby EIPA shall communicate the volume of said increase and the date on which it shall take effect.</p>
                            <h4 className="uk-text-muted">Payment</h4>
                            <p>Payment must be made within 30 days from the date of invoice, in a way to be indicated by EIPA and in the currency in which the statement of expenses was drawn up. Contestation of the amount of the statements of expenses shall not suspend the fulfilment of the payment obligation. In the case of large contracts and/or contracts with a term of more than three months, an advance of at least 20% will be charged on commencement of the contract and/or the expenses due will be charged periodically. If client fails to fulfil his payment obligation within the term of 30 days, then client shall be in default by operation of law. In that event, client shall owe an interest of 1% per month, unless the statutory interest rate is higher, in which case the statutory interest rate shall apply. The interest on the amount due and payable shall be calculated as from the day the client is in default until the moment he has paid the amount in full. EIPA’s claims against client shall become due on demand in the event that client’s company is wound up, attached, declared bankrupt, or if a suspension of payment is granted. EIPA shall be entitled to have the payments made by the client go first of all to reduce the costs, subsequently to reduce the interest still due and finally to reduce the principal sum and the current interest. EIPA shall have the right, without this leading EIPA to be in default, to refuse an offer for payment, if the client designates a different sequence of attribution. EIPA shall be entitled to refuse full payment of the principal sum, if said payment does not include the interest still due, the current interest and the costs.</p>
                            <h4 className="uk-text-muted">Retention of Title</h4>
                            <p>All goods delivered by EIPA, possibly also including designs, sketches, drawings, films, software, (electronic) files, etc., shall remain EIPA’s property until client has fulfilled all of his obligations under all agreements concluded with EIPA. Client shall not be authorised to pledge or encumber in any way the goods falling under the retention of title. If third parties seize goods delivered subject to retention of title or wish to establish or assert a right to them, client shall be held to inform EIPA thereof as soon as can reasonably expected. The client shall undertake to insure the goods delivered subject to retention of title and to keep them insured against damage caused by fire, explosion and water as well as against theft and make this insurance policy available for inspection on first demand. Goods delivered by EIPA falling under the retention of title by virtue of the stipulations under 1. of the present article, may only be sold on within the framework of normal business activities and must never be used as instrument of payment. In the event that EIPA wishes to exercise his ownership rights mentioned in the present article, client shall give EIPA or third parties to be appointed by EIPA, now for then, unconditional and irrevocable permission to access all sites and locations where EIPA’s property might be found and to take these goods back.</p>
                            <h4 className="uk-text-muted">Collection Charges</h4>
                            <p>If the client is in default of, or fails to meet, one or more of his obligations, all reasonable costs incurred to obtain payment out of court shall be borne by the client. The client shall in any case owe collection charges in the case of a monetary claim. The collection charges shall be calculated in accordance with the methods used in collection procedures and generally recognised in Dutch case law. If EIPA demonstrates that it has incurred higher expenses, which were necessary in reason, said expenses shall also qualify for reimbursement. The reasonable judicial and execution costs possibly incurred shall equally be borne by client. The client shall owe interest over the collection charges.</p>
                            <h4 className="uk-text-muted">Inspection & Complaints</h4>
                            <p>The client must notify EIPA in writing of complaints about the work done within 8 days following their detection, but no later than within 14 days following completion of the work concerned. The notice of default must give as detailed a description as possible of the shortcoming, so that EIPA is in a position to respond adequately. If a complaint proves to be well-founded, EIPA shall yet do the work as agreed upon, unless such has become demonstrably useless in the meantime to the client. The client must notify EIPA in writing if the latter is the case. If it is no longer possible or useful to still do the work with respect to the provision of services agreed upon, EIPA shall only be liable within the limits of article 15.</p>
                            <h4 className="uk-text-muted">Cancellation</h4>
                            <p>Both parties shall be entitled to cancel the agreement at all times. If the agreement is terminated prematurely by client, EIPA shall be entitled to compensation of the loss of capacity utilisation to be demonstrated caused by said premature termination, unless the termination is based on facts and circumstances which can be attributed to EIPA. Client shall furthermore be held in that event to pay the statement of expenses for the work done up till that moment. The preliminary results of the work done up till that moment shall therefore be put at client’s disposal subject to approval. If the agreement is terminated prematurely by EIPA, EIPA shall see to it in conjunction with client that the work still to be done be transferred to third parties, unless the termination is based on facts and circumstances which can be attributed to client. If the transfer of the work still to be done entails extra costs for EIPA, said costs shall be charged to client.</p>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}
